# Generated by Django 4.0.3 on 2022-05-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarPickUp', '0003_auto_20220509_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentvideo',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentvideo',
            name='video_record',
            field=models.FileField(default=0, upload_to='records'),
            preserve_default=False,
        ),
    ]
