# Generated by Django 4.0.3 on 2022-05-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarPickUp', '0004_rename_path_studentvideo_video_path_and_more'),
        ('GuitarPickUp', '0005_auto_20220522_2025'),
    ]

    operations = [
    ]
